services:
  stock-checker:
    build: .
    container_name: amazon-stock-checker
    restart: unless-stopped
    shm_size: "512mb"
    volumes:
      - /mnt/user/appdata/amazon-stock-checker/config:/config
